---
abstract: 'A size-aware in-memory cache optimized for speed'
author:
  - 'Phil Pollard <bennie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.140630'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Cache-Bounded
no_index:
  directory:
    - t
    - inc
    - t
provides:
  Cache::Bounded:
    file: lib/Cache/Bounded.pm
    version: '1.08'
requires:
  Test::More: '0'
  Test::Simple: '0'
  perl: '5.006001'
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=Cache-Bounded
  repository: git://github.com/bennie/perl-Cache-Bounded.git
version: '1.08'
