--- #YAML:1.0
name:               Cache-Bounded
version:            1.07
abstract:           Parse and analyze RCS files
author:
    - Phil Pollard <bennie@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:               5.008001
    Test::Simple:       0
resources:
    bugtracker:
        web:  https://rt.cpan.org/Dist/Display.html?Name=Cache-Bounded
    repository:
        type:  git
        url:   git://github.com/bennie/perl-Cache-Bounded.git
        web:   http://github.com/bennie/perl-Cache-Bounded
no_index:
    directory:
        - t
        - inc
provides:
    Cache::Bounded:
        file: lib/Cache/Bounded.pm
        version: 1.07
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
